[build]
target = "../riscv64g-unknown-mizu-elf.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.riscv64g-unknown-mizu-elf]
rustflags = ["-C", "link-arg=-Ttemp/link.x", "-C", "target-feature=-c", "-Copt-level=1"]
linker = "ld.lld"
runner = ["riscv64-unknown-elf-objdump", "--disassemble", "--disassembler-color=terminal", "--visualize-jumps=color", "-C"]
