[build]
target = "../riscv64g-unknown-mizu-elf.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.riscv64g-unknown-mizu-elf]
rustflags = ["-Clink-arg=-Ttemp/link.x", "-Ctarget-feature=-c", "-Copt-level=z", "-Cforce-unwind-tables", "-Clink-arg=-Ttemp/eh_frame.ld"]
linker = "ld.lld"
runner = ["riscv64-unknown-elf-objdump", "--disassemble", "--disassembler-color=terminal", "--visualize-jumps=color", "-C"]
