[package]
name = "temp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false }
mizu-hal = { path = "../hal-rs", features = [] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
