[package]
name = "mizu-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
hal-types = { version = "0.1.0", path = "../hal-types" }
mini-backtrace = { version = "0.1.4", path = "../../mini-backtrace" }
rand_core = "0.6.4"

[features]
backtrace = []
